version: "3.3"
services:
  frontend:
    image: registry.gitlab.com/sk_inno/front:latest
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`sk.amics-tech.ru`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.services.frontend.loadbalancer.server.port=3001"
        - "traefik.http.routers.frontend.service=frontend"
        - "traefik.http.routers.frontend.tls.certresolver=leresolver"
        - "traefik.http.routers.frontend.tls.domains[0].main=sk.amics-tech.ru"
    networks:
      - public
networks:
  public:
    external: true
