export const FETCH_CARDS = "FETCH_CARDS";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const CREATE_CARD = "CREATE_CARD";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const UPDATE_CARD = "UPDATE_CARD";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const DELETE_CARD = "DELETE_CARD";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const API_ERROR = "CARDS_API_ERROR";

export const GET_CARD_STATUSES = " GET_CARD_STATUSES"
export const GET_CARD_TYPES = " GET_CARD_TYPES"
